Add FAQ to documentation
spockframework/spock pull request #1212
Opened 2020-09-02 02:19 UTC by kriegaex

For now, there are two FAQ items explaining optional dependencies in general and
explaining why there are two class mocking variants ByteBuddy vs. CGLIB.

Closes #1165.

2020-09-02 19:39 UTC, szpak submitted a review, later dismissed

2020-09-07 15:48 UTC, leonard84 requested changes
It should also be mentioned, that spock will use ByteBuddy if both libraries are on the classpath.

Also please format according to [one sentence per line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line), I know that not every part of the guide follows that guideline yet, but new documentation should.

2020-09-07 15:48 UTC, leonard84 commented on docs/faq.adoc
> +may safely continue to use CGLIB if e.g. your tests use it in another context already. If you have no compelling reasons
```suggestion
CGLIB is in legacy support mode, we will support it as long as the maintenance effort is relatively low. So you
may continue to use CGLIB for now if e.g. your tests use it in another context already. If you have no compelling reasons
```

2020-09-07 15:48 UTC, leonard84 commented on docs/faq.adoc
> +  * Either CGLIB (artifact `cglib:cglib-nodep`) or ByteBuddy (artifact `net.bytebuddy:byte-buddy`) are required for
```suggestion
  * Either ByteBuddy (artifact `net.bytebuddy:byte-buddy`) or CGLIB (artifact `cglib:cglib-nodep`) are required for
```

2020-09-07 15:48 UTC, leonard84 commented on docs/faq.adoc
> +== Why are there two options (CGLIB vs ByteBuddy) for mocking classes?
```suggestion
== Why are there two options (ByteBuddy vs CGLIB) for mocking classes?
```

2020-09-08 19:59 UTC, leonard84 approved these changes

2020-09-08 20:47 UTC, merged