IDEA settings, vcs.xml: add CommitMessageInspectionProfile
spockframework/spock pull request #1246
Opened 2020-12-19 05:50 UTC by kriegaex

This configures a visible right margin at column 80 and word wrap for the commit
dialogue in IntelliJ IDEA.

![image](https://user-images.githubusercontent.com/1537384/102682019-b8059300-41f8-11eb-856d-a9bf0613f217.png)

![image](https://user-images.githubusercontent.com/1537384/102682024-be940a80-41f8-11eb-9721-ea9c4c2b11a9.png)

2020-12-25 15:42 UTC, leonard84 requested changes

2020-12-25 15:42 UTC, leonard84 commented on .idea/vcs.xml
> +        <option name="RIGHT_MARGIN" value="80" />
```suggestion
        <option name="RIGHT_MARGIN" value="72" />
```

2020-12-25 15:42 UTC, leonard84 commented on .idea/vcs.xml
> +        <option name="RIGHT_MARGIN" value="80" />
```suggestion
        <option name="RIGHT_MARGIN" value="50" />
```

2020-12-25 15:42 UTC, leonard84 commented on .idea/vcs.xml
> +  <component name="CommitMessageInspectionProfile">
If we formalize these suggestions I'd like to follow https://chris.beams.io/posts/git-commit/

2020-12-26 16:24 UTC, leonard84 approved these changes

2020-12-26 16:26 UTC, merged

2021-01-08 00:59 UTC, kriegaex commented
I just noticed strange unstaged changes in _vcs.xml_ after I pulled the new master. They seem to originate in your suggested changes and look like this:

![image](https://user-images.githubusercontent.com/1537384/103961175-7e380480-5186-11eb-9d30-e68f9afed544.png)

What the diff basically say is:
  * The commit message word-wrap width of 72 characters is the default, which is why it gets removed by IDEA automatically.
  * The last line feed in the file should be obligatory, but IDEA seems to prefer to always commit without one.

I did not notice that at first when accepting the changes or maybe they came up after a recent IDEA update on my machine, but now I cannot switch branches because of uncommitted changes in that file anymore. In my own projects I never commit any IDE config files, but Spock has some, which is why I suggested the changes.

Anyway, it is annoying enough for me to ask you, @leonard84, if you agree with me pushing one more commit to this branch and re-merging it. You may want to test first, if you also experience the same symptoms.