Add !! as opt-out operator for assertions...
spockframework/spock pull request #1532
Opened 2022-10-02 11:44 UTC by leonard84

it will turn of the condition tracking, i.e., the capturing of values.
And for implicit conditions it will remove any special handling.

2022-10-02 11:45 UTC, leonard84 commented
@timyates IIRC you also requested this feature this year.

2023-04-17 12:29 UTC, Vampire requested changes

2023-04-17 12:29 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/docs/primer/ConditionsSpec.groovy
> +  def "normal condition rendering"() {
Not used in the docs

2023-04-17 12:29 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionEvaluation.groovy
> +import static java.lang.Math.min
Is once not enough? :-D

2023-04-17 12:47 UTC, timyates commented
Does this interact with this existing test?

https://github.com/spockframework/spock/blob/e177b39868d487d14a34f8d704cc431060a0e193/spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionEvaluation.groovy#L293-L298

(ie: does `!!true` now become a check for `true` with no output?)

2023-04-17 14:10 UTC, Vampire commented
> (ie: does !!true now become a check for true with no output?)

I would say as it is an implicit assertion `!!true` becomes `true` **without** being checked.
Same for `!!false`, it would become `false` without being checked and thus would not make the test fail.

2023-05-05 15:42 UTC, leonard84 commented
@Vampire / @timyates can I take your comments as implicit agreement to the base idea and choice of `!!` ?

2023-08-16 09:59 UTC, Vampire approved these changes

2023-08-21 15:06 UTC, merged