Use multiple locks in ByteBuddyMockFactory to reduce lock contention
spockframework/spock pull request #1778
Opened 2023-09-03 10:42 UTC by AndreasTu

Changed locking scheme in ByteBuddyMockFactory from a single global lock CACHE to cacheLocks with size 16. 
The used TypeCachingLock from cacheLocks depends on the hashcode of TypeCache.SimpleKey, 
which aggregates the types and settings to mock.

The old global CACHE lock did block Threads regardless, if they try to mock the same type or not.

This is a similar fix as in Mockito:
[Mockito 3095](https://github.com/mockito/mockito/pull/3095)

2023-09-04 21:48 UTC, Vampire requested changes

2023-09-04 21:48 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy
> +  def "cacheLockingStressTest"(String test, MockSpec mockSpecA, MockSpec mockSpecB) {
iirc, we usually do not declare the data variables explicitly except when testing that functionality.
And especially not ones only used in the naming pattern like `test`.

2023-09-04 21:48 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy
> +    return new MockSpec(mockedType, Arrays.asList(interfaces))
```suggestion
    return new MockSpec(mockedType, interfaces as List)
```

2023-09-04 21:48 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy
> +    }
```suggestion
    mockFeature.interfaces.each {
      assert it.isAssignableFrom(mockClass)
    }
```

2023-09-04 21:48 UTC, Vampire commented on spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy
> +      })
```suggestion
      CompletableFuture.runAsync {
        phaser.arriveAndAwaitAdvance()
        try {
          for (int i = 0; i < iterations; i++) {
            code.run()
          }
        } finally {
          phaser.arrive()
        }
      }
```

2023-09-04 21:48 UTC, Vampire commented on spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java
> +   * See the hashcode implementation of the {@code TypeCache.SimpleKey}, which has {@code Set} semantics.
```suggestion
   * See the {@code hashCode} implementation of the {@code TypeCache.SimpleKey}, which has {@code Set} semantics.
```

2023-09-04 22:04 UTC, AndreasTu commented on spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java
> +  private final TypeCachingLock[] cacheLocks;
I prefer the constructor.

2023-09-04 22:05 UTC, AndreasTu commented on spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java
> +    TypeCache.SimpleKey key = new TypeCache.SimpleKey(type, additionalInterfaces);
I have corrected the commit and PR message. Only the types are relevant.

2023-09-10 22:11 UTC, Vampire approved these changes
LGTM, thx

2023-09-10 22:14 UTC, merged