Prevent StackOverflowError when filtering exception cause loops
spockframework/spock pull request #1922
Opened 2024-03-17 04:22 UTC by Vampire

2024-03-17 04:22 UTC, Vampire commented
* **#1923** <a href="https://app.graphite.dev/github/pr/spockframework/spock/1923?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1922** <a href="https://app.graphite.dev/github/pr/spockframework/spock/1922?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-17 16:22 UTC, leonard84 requested changes

2024-03-17 16:22 UTC, leonard84 commented on spock-core/src/main/java/org/spockframework/runtime/StackTraceFilter.java
> +    filter(throwable, new HashSet<>());
If we add this, then we should use the same method that the `java.lang.Throwable#lockedPrintStackTrace` uses
```suggestion
    filter(throwable, Collections.newSetFromMap(new IdentityHashMap<>()));
```

2024-03-18 23:18 UTC, leonard84 approved these changes

2024-03-18 23:23 UTC, merged