Move workflows Kotlin dependencies for Gradle to version catalog
spockframework/spock pull request #2066
Opened 2024-12-30 05:06 UTC by Vampire

This contains old Kotlin version to test that Renovate now properly updates it.

2024-12-30 05:06 UTC, Vampire commented
* **#2066** <a href="https://app.graphite.dev/github/pr/spockframework/spock/2066?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/spockframework/spock/2066?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-06 16:49 UTC, leonard84 requested changes

2025-01-06 16:49 UTC, leonard84 commented on gradle/libs.versions.toml
> +workflows-kotlin-scripting-compiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler", version.ref = "workflows-kotlin" }
I don't think we need 4 layers
```suggestion
workflows-kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "workflows-kotlin" }
workflows-kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "workflows-kotlin" }
workflows-kotlin-mainKts = { module = "org.jetbrains.kotlin:kotlin-main-kts", version.ref = "workflows-kotlin" }
workflows-kotlin-scriptingCompiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler", version.ref = "workflows-kotlin" }
```

2025-01-07 18:15 UTC, leonard84 approved these changes

2025-01-07 22:30 UTC, merged